/-
Copyright (c) 2026 Eduardo Nava-Hernandez. All rights reserved.
Released under the NRS Noncommercial License 1.0.0 as described in the file LICENSE.
Authors: Eduardo Nava-Hernandez
-/
module

public import NavaRobertsonIndependent.Mathematics.D23d_BandWidth
public import NavaRobertsonIndependent.Mathematics.D37f_LightCone
public import Mathlib.Analysis.Matrix.Normed
public import Mathlib.Analysis.Normed.Algebra.Exponential

/-!
# D37g — Lieb–Robinson bound for transport

`T_d` is, up to shift and scale, the Dirichlet discretization of `−d²/dx²` on `[−1, 1]`. In
continuous time `U(t) = exp(−i t T_d)`, and outside the cone of `D37f` the amplitude decays
faster than any exponential: `|U(t)ᵢⱼ| ≤ |t|^r / r! · e^{|t|}`, `r = |i − j|`. The terms
`n < r` of `Σₙ (−it)ⁿ/n! (T_dⁿ)ᵢⱼ` vanish (`D37f`), `|(T_dⁿ)ᵢⱼ| ≤ 1` (`D23d`), and
`m! r! ≤ (m + r)!` bounds the tail.

## Main results

- `LiebRobinson.lieb_robinson` : `|U(t)ᵢⱼ| ≤ |t|^r / r! · e^{|t|}`.
-/

@[expose] public noncomputable section

open TransportPosition LightCone BandWidth

namespace LiebRobinson

variable {d : ℕ}

/-! ## 1. Entries of powers of `T_d` are bounded by `1` -/

theorem norm_pow_apply_le (hd : 2 ≤ d) (n : ℕ) (v : Hd d) :
    ‖Matrix.toEuclideanLin (Td d ^ n) v‖ ≤ ‖v‖ := by
  induction n generalizing v with
  | zero => simp
  | succ n ih =>
    rw [pow_succ, Matrix.toEuclideanLin, Matrix.toLpLin_mul_same, LinearMap.comp_apply]
    exact (ih _).trans (norm_TdOp_le hd v)

theorem norm_entry_pow_le (hd : 2 ≤ d) (n : ℕ) (i j : Fin d) : ‖(Td d ^ n) i j‖ ≤ 1 := by
  have h := norm_pow_apply_le hd n (EuclideanSpace.single j (1 : ℂ))
  rw [EuclideanSpace.single, PiLp.norm_single, norm_one] at h
  have hc : (Matrix.toEuclideanLin (Td d ^ n) (EuclideanSpace.single j (1 : ℂ))) i =
      (Td d ^ n) i j := by
    simp only [Matrix.toEuclideanLin, Matrix.toLpLin_apply, Matrix.mulVec, dotProduct]
    simp
  rw [← hc]
  exact (PiLp.norm_apply_le _ i).trans h

/-! ## 2. Entries of the evolution `U(t) = exp(−i t T_d)` -/

/-- The evolution generated by transport, in continuous time. -/
def U (d : ℕ) (t : ℝ) : Matrix (Fin d) (Fin d) ℂ :=
  NormedSpace.exp ((-(Complex.I * t)) • Td d)

theorem entry_exp (M : Matrix (Fin d) (Fin d) ℂ) (i j : Fin d) :
    NormedSpace.exp M i j = ∑' n : ℕ, ((n.factorial : ℂ)⁻¹) * (M ^ n) i j := by
  let _ : NormedRing (Matrix (Fin d) (Fin d) ℂ) := Matrix.linftyOpNormedRing
  let _ : NormedAlgebra ℂ (Matrix (Fin d) (Fin d) ℂ) := Matrix.linftyOpNormedAlgebra
  have hs : Summable (fun n : ℕ => ((n.factorial : ℂ)⁻¹) • M ^ n) :=
    NormedSpace.expSeries_summable' M
  rw [congrFun (NormedSpace.exp_eq_tsum ℂ) M]
  have h1 := Pi.tsum_apply (x := i) hs
  have h2 := Pi.tsum_apply (x := j) (Pi.summable.mp hs i)
  simp only [Matrix.smul_apply, smul_eq_mul] at h1 h2
  exact (congrFun h1 j).trans h2

theorem entry_U (t : ℝ) (i j : Fin d) :
    U d t i j = ∑' n : ℕ, ((n.factorial : ℂ)⁻¹) * ((-(Complex.I * t)) ^ n * (Td d ^ n) i j) := by
  rw [U, entry_exp]
  congr 1; ext n
  rw [smul_pow, Matrix.smul_apply, smul_eq_mul]

/-! ## 3. The Lieb–Robinson bound -/

theorem factorial_tail (x : ℝ) (hx : 0 ≤ x) (m r : ℕ) :
    x ^ (m + r) / ((m + r).factorial : ℝ) ≤
      x ^ r / (r.factorial : ℝ) * (x ^ m / (m.factorial : ℝ)) := by
  have hfac : ((m.factorial : ℝ) * (r.factorial : ℝ)) ≤ ((m + r).factorial : ℝ) := by
    exact_mod_cast Nat.le_of_dvd (Nat.factorial_pos _)
        (Nat.factorial_mul_factorial_dvd_factorial_add m r)
  have hpos : (0 : ℝ) < (m.factorial : ℝ) * (r.factorial : ℝ) := by positivity
  calc x ^ (m + r) / ((m + r).factorial : ℝ)
      ≤ x ^ (m + r) / ((m.factorial : ℝ) * (r.factorial : ℝ)) :=
        div_le_div_of_nonneg_left (by positivity) hpos hfac
    _ = x ^ r / (r.factorial : ℝ) * (x ^ m / (m.factorial : ℝ)) := by
        rw [pow_add]; field_simp

/-- **Lieb–Robinson bound.** For the evolution `U(t) = exp(−i t T_d)`,
`|U(t)ᵢⱼ| ≤ |t|^r / r! · e^{|t|}` with `r = |i − j|`: outside the light cone of `D37f` the
amplitude decays faster than any exponential in the distance. -/
theorem lieb_robinson (hd : 2 ≤ d) (t : ℝ) (i j : Fin d) :
    ‖U d t i j‖ ≤
      |t| ^ distPath i j / ((distPath i j).factorial : ℝ) * Real.exp |t| := by
  set r := distPath i j
  set f : ℕ → ℂ := fun n => ((n.factorial : ℂ)⁻¹) * ((-(Complex.I * t)) ^ n * (Td d ^ n) i j)
  set b : ℕ → ℝ := fun n => if n < r then 0 else |t| ^ n / (n.factorial : ℝ)
  have hb0 : ∀ n, 0 ≤ b n := by
    intro n; simp only [b]; split_ifs <;> positivity
  have hfb : ∀ n, ‖f n‖ ≤ b n := by
    intro n
    by_cases hn : n < r
    · simp [f, b, hn, lightCone n i j hn]
    · simp only [f, b, hn, ite_false, norm_mul, norm_inv, Complex.norm_natCast, norm_pow,
        norm_neg, Complex.norm_I, one_mul, Complex.norm_real, Real.norm_eq_abs]
      have := norm_entry_pow_le hd n i j
      have hp : 0 ≤ ((n.factorial : ℝ))⁻¹ * |t| ^ n := by positivity
      calc ((n.factorial : ℝ))⁻¹ * (|t| ^ n * ‖(Td d ^ n) i j‖)
          ≤ ((n.factorial : ℝ))⁻¹ * (|t| ^ n * 1) := by gcongr
        _ = |t| ^ n / (n.factorial : ℝ) := by ring
  have hbs : Summable b :=
    Summable.of_nonneg_of_le hb0 (fun n => by
      simp only [b]; split_ifs
      · positivity
      · exact le_rfl) (Real.summable_pow_div_factorial |t|)
  have hfs : Summable (fun n => ‖f n‖) :=
    Summable.of_nonneg_of_le (fun n => norm_nonneg _) hfb hbs
  have hU : U d t i j = ∑' n, f n := entry_U t i j
  -- the tail of `b` starts at `r`
  have hsplit := hbs.sum_add_tsum_nat_add r
  have hhead : ∑ n ∈ Finset.range r, b n = 0 :=
    Finset.sum_eq_zero fun n hn => by simp [b, Finset.mem_range.mp hn]
  have htail : ∀ m, b (m + r) = |t| ^ (m + r) / ((m + r).factorial : ℝ) := by
    intro m; simp [b]
  have hgs : Summable (fun m : ℕ => |t| ^ r / (r.factorial : ℝ) * (|t| ^ m / (m.factorial : ℝ))) :=
    (Real.summable_pow_div_factorial |t|).mul_left _
  have hexp : ∑' m : ℕ, |t| ^ m / (m.factorial : ℝ) = Real.exp |t| := by
    rw [Real.exp_eq_exp_ℝ, congrFun NormedSpace.exp_eq_tsum_div]
  calc ‖U d t i j‖ = ‖∑' n, f n‖ := by rw [hU]
    _ ≤ ∑' n, ‖f n‖ := norm_tsum_le_tsum_norm hfs
    _ ≤ ∑' n, b n := Summable.tsum_le_tsum hfb hfs hbs
    _ = ∑' m, b (m + r) := by rw [← hsplit, hhead, zero_add]
    _ ≤ ∑' m : ℕ, |t| ^ r / (r.factorial : ℝ) * (|t| ^ m / (m.factorial : ℝ)) := by
        refine Summable.tsum_le_tsum (fun m => ?_) ((summable_nat_add_iff r).mpr hbs) hgs
        rw [htail]; exact factorial_tail |t| (abs_nonneg t) m r
    _ = |t| ^ r / (r.factorial : ℝ) * Real.exp |t| := by rw [tsum_mul_left, hexp]

end LiebRobinson

end
