/-
Copyright (c) 2026 Eduardo Nava-Hernandez. All rights reserved.
Released under the NRS Noncommercial License 1.0.0 as described in the file LICENSE.
Authors: Eduardo Nava-Hernandez
-/
module

public import NavaRobertsonIndependent.Mathematics.D40_SpeedLimitUncertainty
public import NavaRobertsonIndependent.Mathematics.D37d_CubePythagoras

/-!
# D41 — Mandelstam–Tamm and Cramér–Rao on `T_d : P_d`

By the Heisenberg equation of `D38`, the tension `⟨K_d⟩ = ⟨i[T_d, P_d]⟩` is the rate of change of
`⟨P_d⟩` under the evolution generated by `T_d`, whether the parameter is time or a displacement
`θ` imprinted by `exp(−iθT_d)`. Robertson for `(T_d, P_d)` therefore reads in two ways:

* **Mandelstam–Tamm**: `⟨K_d⟩² ≤ 4 Var T_d · Var P_d`, the speed of `⟨P_d⟩` is bounded by the
  energy spread of transport;
* **quantum Cramér–Rao**: the error-propagation Fisher information of `P_d`,
  `⟨K_d⟩² / Var P_d`, is at most the quantum Fisher information `4 Var T_d` of a pure state.

Both are one ratio, `mtRatio d ψ = ⟨K_d⟩² / (4 Var T_d · Var P_d) ≤ 1`. At the maximal-tension
state it equals `1 / C_Nava(d)² = cos² θ_NRS(d)`: both bounds are attained exactly at
`d = 2, 3` and missed by the algebraic quantum from `d = 4` on.

## Main results

- `GroupVelocity.mandelstamTamm` : `⟨K_d⟩² ≤ 4 Var T_d · Var P_d`.
- `GroupVelocity.cramerRao` : `fisherP d ψ ≤ qfi d ψ`.
- `GroupVelocity.mtRatio_psiStar` : at `ψ*`, the ratio is `1 / C_Nava(d)²`.
- `GroupVelocity.mtRatio_psiStar_eq_one_iff`, `GroupVelocity.mtRatio_psiStar_lt_one` : both
  bounds are attained at `ψ*` iff `d = 2, 3`.
- `GroupVelocity.mtRatioG_axis_x` (and `_y`, `_z`) : on the cube each axis has ratio
  `1 / C_Nava(d_axis)²` at `Ψ*`.
- `GroupVelocity.mtRatioG_total_cube` : on `d × d × d` the total pair `(ΣT, ΣP)` has ratio
  `1 / C_Nava(d)²` at `Ψ*`: the three axes add speed and spread without closing the gap.
-/

@[expose] public noncomputable section

open TransportPosition NRSInequality NearMaxTension EigenvectorSaturation Gnomon GramStep
open SpectralExtremal PathGraph3DNRS CubeSpectrum CubePythagoras

namespace GroupVelocity

variable {d : ℕ}

theorem one_le_CoherenceConstant (hd : 2 ≤ d) : 1 ≤ CoherenceConstant d := by
  rw [CoherenceConstant_eq_one_add_geometricGap]
  linarith [geometricGap_nonneg hd]

/-- The fraction of the Mandelstam–Tamm and Cramér–Rao bounds attained at `ψ`. -/
def mtRatio (d : ℕ) (ψ : Hd d) : ℝ :=
  tension d ψ ^ 2 / (4 * (variance (TdOp d) ψ * variance (PdOp d) ψ))

/-- The quantum Fisher information `4 Var T_d` of a pure state for the generator `T_d`. -/
def qfi (d : ℕ) (ψ : Hd d) : ℝ := 4 * variance (TdOp d) ψ

/-- The error-propagation Fisher information of `P_d`: `(∂_θ⟨P_d⟩)² / Var P_d`. -/
def fisherP (d : ℕ) (ψ : Hd d) : ℝ := tension d ψ ^ 2 / variance (PdOp d) ψ

/-- **Mandelstam–Tamm.** The rate of `⟨P_d⟩` is at most `2 σ_T σ_P`. -/
theorem mandelstamTamm (ψ : Hd d) :
    tension d ψ ^ 2 ≤ 4 * (variance (TdOp d) ψ * variance (PdOp d) ψ) := by
  have := variance_mul_variance_ge d ψ
  unfold tension
  linarith

/-- **Quantum Cramér–Rao.** Estimating with `P_d` gathers at most the quantum Fisher
information. -/
theorem cramerRao (ψ : Hd d) (hP : 0 < variance (PdOp d) ψ) : fisherP d ψ ≤ qfi d ψ := by
  rw [fisherP, qfi, div_le_iff₀ hP]
  linarith [mandelstamTamm ψ]

/-- The Cramér–Rao efficiency is the Mandelstam–Tamm ratio. -/
theorem fisherP_div_qfi (ψ : Hd d) : fisherP d ψ / qfi d ψ = mtRatio d ψ := by
  rw [fisherP, qfi, mtRatio, div_div]
  ring

/-- At the maximal-tension state the ratio is `1 / C_Nava(d)²`. -/
theorem mtRatio_psiStar (hd : 2 ≤ d) : mtRatio d (psiStar d) = 1 / CoherenceConstant d ^ 2 := by
  have hd1 : (d : ℝ) - 1 ≠ 0 := by
    have : (2 : ℝ) ≤ d := by exact_mod_cast hd
    linarith
  have hC : CoherenceConstant d ≠ 0 := by linarith [one_le_CoherenceConstant hd]
  rw [mtRatio, tension_psiStar hd, variance_mul_variance hd, commutatorConstant_half_sq hd,
    ← CoherenceConstant_eq_one_add_geometricGap]
  field_simp
  ring

/-- Both bounds are attained at `ψ*` exactly at `d = 2, 3`. -/
theorem mtRatio_psiStar_eq_one_iff (hd : 2 ≤ d) : mtRatio d (psiStar d) = 1 ↔ d = 2 ∨ d = 3 := by
  have hC := one_le_CoherenceConstant hd
  rw [mtRatio_psiStar hd, ← CoherenceConstant_eq_one_iff d hd, div_eq_one_iff_eq (by positivity),
    eq_comm, pow_eq_one_iff_of_nonneg (by linarith) two_ne_zero]

/-- From `d = 4` both bounds are missed at `ψ*` by the algebraic quantum. -/
theorem mtRatio_psiStar_lt_one (hd : 4 ≤ d) : mtRatio d (psiStar d) < 1 := by
  have hC := one_lt_CoherenceConstant_of_four_le d hd
  rw [mtRatio_psiStar (by omega), div_lt_one (by positivity)]
  nlinarith

/-! ## The cube -/

/-- The Mandelstam–Tamm ratio of a pair `(L, M)` at `Ψ` on any finite site set. -/
def mtRatioG {ι : Type*} [Fintype ι] (L M : EuclideanSpace ℂ ι →ₗ[ℂ] EuclideanSpace ℂ ι)
    (Ψ : EuclideanSpace ℂ ι) : ℝ :=
  tensionG L M Ψ ^ 2 / (4 * (varianceG L Ψ * varianceG M Ψ))

/-- `mtRatio_psiStar` with the tension written out. -/
theorem mtRatio_psiStar' {d : ℕ} (hd : 2 ≤ d) :
    (2 / ((d : ℝ) - 1)) ^ 2 / (4 * (variance (TdOp d) (psiStar d) * variance (PdOp d) (psiStar d)))
      = 1 / CoherenceConstant d ^ 2 := by
  rw [← mtRatio_psiStar hd, mtRatio, tension_psiStar hd]

section Cube

variable {dx dy dz : ℕ} (hx : 2 ≤ dx) (hy : 2 ≤ dy) (hz : 2 ≤ dz)
include hx hy hz

theorem mtRatioG_axis_x :
    mtRatioG (TX dx dy dz) (PX dx dy dz) (PsiStar3D dx dy dz) = 1 / CoherenceConstant dx ^ 2 := by
  obtain ⟨hT, hP, -, ht⟩ := stats_axis_x hx hy hz
  rw [mtRatioG, hT, hP, ht, mtRatio_psiStar' hx]

theorem mtRatioG_axis_y :
    mtRatioG (TY dx dy dz) (PY dx dy dz) (PsiStar3D dx dy dz) = 1 / CoherenceConstant dy ^ 2 := by
  obtain ⟨hT, hP, -, ht⟩ := stats_axis_y hx hy hz
  rw [mtRatioG, hT, hP, ht, mtRatio_psiStar' hy]

theorem mtRatioG_axis_z :
    mtRatioG (TZ dx dy dz) (PZ dx dy dz) (PsiStar3D dx dy dz) = 1 / CoherenceConstant dz ^ 2 := by
  obtain ⟨hT, hP, -, ht⟩ := stats_axis_z hx hy hz
  rw [mtRatioG, hT, hP, ht, mtRatio_psiStar' hz]

omit hx hy hz in
theorem opCommutator_add_left {ι : Type*} [Fintype ι]
    (A B C : EuclideanSpace ℂ ι →ₗ[ℂ] EuclideanSpace ℂ ι) :
    opCommutator (A + B) C = opCommutator A C + opCommutator B C := by
  simp only [opCommutator, LinearMap.add_comp, LinearMap.comp_add]
  abel

omit hx hy hz in
theorem opCommutator_add_right {ι : Type*} [Fintype ι]
    (A B C : EuclideanSpace ℂ ι →ₗ[ℂ] EuclideanSpace ℂ ι) :
    opCommutator A (B + C) = opCommutator A B + opCommutator A C := by
  simp only [opCommutator, LinearMap.add_comp, LinearMap.comp_add]
  abel

omit hx hy hz in
theorem opCommutator_swap {ι : Type*} [Fintype ι]
    (A B : EuclideanSpace ℂ ι →ₗ[ℂ] EuclideanSpace ℂ ι) :
    opCommutator B A = -opCommutator A B := by
  simp only [opCommutator, neg_sub]

omit hx hy hz in
/-- Only the pair of the same axis collides: `i[ΣT, ΣP] = K_x + K_y + K_z`. -/
theorem observableTension_total :
    observableTension (TX dx dy dz + TY dx dy dz + TZ dx dy dz)
      (PX dx dy dz + PY dx dy dz + PZ dx dy dz) = Ktotal := by
  have xy : opCommutator (TX dx dy dz) (PY dx dy dz) = 0 := commutator_axes_xy dx dy dz _ _
  have xz : opCommutator (TX dx dy dz) (PZ dx dy dz) = 0 := commutator_axes_xz dx dy dz _ _
  have yz : opCommutator (TY dx dy dz) (PZ dx dy dz) = 0 := commutator_axes_yz dx dy dz _ _
  have yx : opCommutator (TY dx dy dz) (PX dx dy dz) = 0 := by
    rw [opCommutator_swap]; exact neg_eq_zero.mpr (commutator_axes_xy dx dy dz _ _)
  have zx : opCommutator (TZ dx dy dz) (PX dx dy dz) = 0 := by
    rw [opCommutator_swap]; exact neg_eq_zero.mpr (commutator_axes_xz dx dy dz _ _)
  have zy : opCommutator (TZ dx dy dz) (PY dx dy dz) = 0 := by
    rw [opCommutator_swap]; exact neg_eq_zero.mpr (commutator_axes_yz dx dy dz _ _)
  simp only [observableTension, opCommutator_add_left, opCommutator_add_right, xy, xz, yz, yx,
    zx, zy, add_zero, zero_add, Ktotal, KX, KY, KZ, smul_add]

theorem tensionG_total :
    tensionG (TX dx dy dz + TY dx dy dz + TZ dx dy dz) (PX dx dy dz + PY dx dy dz + PZ dx dy dz)
        (PsiStar3D dx dy dz) = 2 / ((dx : ℝ) - 1) + 2 / ((dy : ℝ) - 1) + 2 / ((dz : ℝ) - 1) := by
  have hn : inner ℂ (PsiStar3D dx dy dz) (PsiStar3D dx dy dz) = 1 :=
    inner_self_of_norm_one (by
      rw [PsiStar3D_eq_eX]; exact norm_prodAlong_eq_one _ (norm_psiStar hx) (norm_rest hy hz))
  rw [tensionG, observableTension_total, tensionTotal_psiStar hx hy hz, inner_smul_right, hn,
    mul_one, Complex.ofReal_re]

end Cube

/-- **Mandelstam–Tamm and Cramér–Rao on the cube.** On `d × d × d`, the total pair `(ΣT, ΣP)`
at `Ψ*` attains exactly the fraction `1 / C_Nava(d)²` of both bounds, as one axis. -/
theorem mtRatioG_total_cube (hd : 2 ≤ d) :
    mtRatioG (TX d d d + TY d d d + TZ d d d) (PX d d d + PY d d d + PZ d d d) (PsiStar3D d d d) =
      1 / CoherenceConstant d ^ 2 := by
  obtain ⟨hT, hP, -, -⟩ := stats_axis_x hd hd hd
  obtain ⟨hT', hP', -, -⟩ := stats_axis_y hd hd hd
  obtain ⟨hT'', hP'', -, -⟩ := stats_axis_z hd hd hd
  rw [mtRatioG, tensionG_total hd hd hd, pythagoras_T hd hd hd, pythagoras_P hd hd hd, hT, hP,
    hT', hP', hT'', hP'', ← mtRatio_psiStar' hd]
  field_simp

end GroupVelocity
